'use client';
import {useEffect,useState} from 'react';

type Item={id?:number; name?:string; role?:string; title?:string; description?:string; excerpt?:string; summary?:string; imageUrl?:string; url?:string; label?:string; icon?:string; status?:string};
const seedTeam=[['MAHAMAT ADAM SALEH','Président','/assets/president.jpg'],['ADAM SATO Abakar','Vice-président',''],['AWA YONGO Madina','Trésorière','/assets/awa-yongo-madina.jpg'],['MOUSSA ABAKAR Sato','Secrétaire exécutif',''],['MOLULI MOKWETI Ibrahim','Secrétaire exécutif adjoint',''],['MBALO TOBIMBE Alain','Conseiller du développement',''],['ABDASSAMAD SATO Abakar','Conseiller religieux',''],['OUSMAN ADAM Abdel','Commissaire aux comptes',''],['SALAHADINE ABDASSAMAD','Inspecteur général','/assets/salahadine.png'],['MBIMBA LITA Adrien','Secrétaire rapporteur',''],['GBANZI','Comptable','']];
export default function Admin(){const [auth,setAuth]=useState(false);const [password,setPassword]=useState('');const [data,setData]=useState<any>(null);const [tab,setTab]=useState('news');const [msg,setMsg]=useState('');const [form,setForm]=useState<any>({});
 async function load(){const r=await fetch('/api/admin/content'); if(r.status===401){setAuth(false);return} const j=await r.json();setData(j);setAuth(true)}
 useEffect(()=>{load()},[]);
 async function login(e:any){e.preventDefault();const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setPassword('');setMsg('');load()}else{const j=await r.json().catch(()=>({}));setMsg(j.error||'Mot de passe incorrect.')}}
 async function save(){setMsg('Enregistrement…');const r=await fetch('/api/admin/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:tab,item:form})});const j=await r.json();setMsg(r.ok?'Enregistré.':j.error||'Erreur');if(r.ok){setForm({});load()}}
 async function remove(type:string,id:number){if(!confirm('Supprimer cet élément ?'))return;await fetch('/api/admin/content',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,id})});load()}
 if(!auth)return <main className="adminWrap"><div className="adminMain container" style={{maxWidth:520}}><div className="adminCard"><h1 style={{color:'var(--navy)'}}>Administration ONGD SALAAM</h1><p className="small">Espace réservé à l’administration. Veuillez saisir le mot de passe administrateur.</p><form className="form" onSubmit={login}><input type="password" placeholder="Mot de passe administrateur" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn dark">Se connecter</button></form>{msg&&<p className="small">{msg}</p>}</div></div></main>;
 const items=data?.[tab]||[]; const fields=tab==='settings'?['key','value']:tab==='team'?['name','role','imageUrl','bio']:tab==='news'?['title','excerpt','content','imageUrl']:tab==='projects'?['title','summary','description','status','imageUrl']:tab==='gallery'?['title','imageUrl','caption']:tab==='documents'?['title','description','url','category']:tab==='social'?['label','url','icon']:['title','description','icon'];
 return <main className="adminWrap"><div className="adminNav"><div className="container"><b>ONGD SALAAM · Administration</b><button className="btn" onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});setAuth(false)}}>Déconnexion</button></div></div><div className="adminMain container"><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:18}}>{['news','projects','team','gallery','documents','social','actions','settings'].map(t=><button key={t} className={tab===t?'btn dark':'btn'} onClick={()=>{setTab(t);setForm({})}}>{t==='news'?'Actualités':t==='projects'?'Projets':t==='team'?'Équipe':t==='gallery'?'Galerie':t==='documents'?'Documents':t==='social'?'Réseaux':t==='settings'?'Paramètres':'Actions'}</button>)}</div><div className="adminGrid"><section className="adminCard"><h2>{form.id?'Modifier':'Ajouter'} · {tab}</h2><div className="form">{fields.map((f:string)=><label key={f}><span className="small">{f}</span>{f==='content'||f==='description'||f==='excerpt'||f==='summary'||f==='bio'||f==='caption'?<textarea value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}/>:<input value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}/>}</label>)}<button className="btn dark" onClick={save}>{form.id?'Mettre à jour':'Publier / enregistrer'}</button>{msg&&<div className="small">{msg}</div>}</div></section><section className="adminCard"><h2>Contenu existant</h2><div className="tableWrap"><table className="table"><thead><tr><th>Élément</th><th>Action</th></tr></thead><tbody>{items.map((x:any)=><tr key={x.id??x.name??x.title}><td><b>{x.name||x.title||x.label}</b><br/><span className="small">{x.role||x.status||x.category||''}</span></td><td>{x.id&&<><button className="btn" onClick={()=>setForm(x)}>Modifier</button> <button className="btn danger" onClick={()=>remove(tab,x.id)}>Supprimer</button></>}</td></tr>)}</tbody></table></div></section></div><div className="notice" style={{marginTop:18}}>Conseil : pour les images, l’administration peut utiliser une URL d’image hébergée. Pour un hébergement de fichiers intégré (upload direct), il faudra connecter un stockage tel que Vercel Blob ou un service équivalent et renseigner ses variables d’environnement.</div></div></main>
}
