import Link from 'next/link';
import {getPublicData} from '@/lib/db';

export const dynamic = 'force-dynamic';

export default async function Home(){
 const d:any=await getPublicData(); const s=d.settings;
 return <>
  <div className="topbar"><div className="container"><span>📍 {s.address}</span><span>✉ {s.email} &nbsp; · &nbsp; ☎ {s.phone}</span></div></div>
  <nav className="nav"><div className="container navin"><Link className="brand" href="#accueil"><img src="/assets/logo.jpg" alt="Logo ONGD SALAAM"/><div><b>ONGD SALAAM</b><small>Solidarité · Assistance · Accompagnement<br/>Amitié · Paix</small></div></Link><input id="navToggle" type="checkbox" className="navToggle" aria-hidden="true"/><div className="links"><Link href="#apropos">À propos</Link><Link href="#actions">Nos actions</Link><Link href="#equipe">Équipe</Link><Link href="#projets">Projets</Link><Link href="#actualites">Actualités</Link><Link href="#contact">Contact</Link><a className="btn" href={s.whatsapp} target="_blank" rel="noopener noreferrer">Suivre sur WhatsApp</a></div><label htmlFor="navToggle" className="mobile" aria-label="Menu">☰</label></div></nav>
  <header id="accueil" className="hero"><div className="container"><div className="heroContent"><span className="eyebrow">{s.heroEyebrow}</span><h1>{s.orgName}<br/><span style={{color:'var(--gold)'}}>{s.heroTitle}</span></h1><p>{s.heroText}</p><div className="heroActions"><Link className="btn" href="#apropos">Découvrir notre mission →</Link><Link className="btn ghost" href="#projets">Voir nos projets</Link></div><div className="heroStats"><div className="stat"><strong>5</strong><span>domaines d’intervention</span></div><div className="stat"><strong>Gbadolite</strong><span>base opérationnelle</span></div><div className="stat"><strong>Nord-Ubangi</strong><span>zone d’engagement</span></div></div></div></div></header>
  <section id="actions" className="section"><div className="container"><div className="head"><div><span className="line"/><h2>Nos domaines d’intervention</h2><p>Des actions orientées vers la protection des personnes vulnérables et le développement de la communauté du Nord-Ubangi.</p></div></div><div className="actions">{d.actions.map((a:any)=><article className="card" key={a.id??a[0]}><div className="icon">{a.icon??a[2]}</div><h3>{a.title??a[0]}</h3><p>{a.description??a[1]}</p></article>)}</div></div></section>
  <section id="apropos" className="section alt"><div className="container aboutGrid"><div className="aboutImg"><img src="/assets/activity-1.jpg" alt="Activité de l’ONGD SALAAM au bureau"/></div><div className="aboutBox"><span className="line"/><h2>{s.aboutTitle}</h2><p className="quote">ONGD SALAAM signifie : Solidarité, Assistance, Accompagnement, Amitié, Paix.</p><p>{s.aboutText}</p><p>La plateforme présente les informations institutionnelles, les activités, les projets, les actualités, les documents et les membres de l’organisation. Ces contenus peuvent être complétés progressivement par l’administration.</p><Link className="btn dark" href="#contact">Nous contacter →</Link></div></div></section>
  <section id="equipe" className="section teamSection"><div className="container"><div className="head"><div><span className="line"/><h2>Notre équipe</h2><p>Les responsabilités ci-dessous reprennent les informations communiquées par l’organisation. Les profils sans photo restent volontairement neutres jusqu’à réception d’un visuel officiel.</p></div></div><div className="teamGrid">{d.team.map((m:any)=><article className="person" key={m.id??m[0]}>{m.imageUrl||m[2]?<img src={m.imageUrl||m[2]} alt={m.name||m[0]}/>:<div className="placeholder">👤</div>}<div className="personInfo"><h3>{m.name||m[0]}</h3><p>{m.role||m[1]}</p></div></article>)}</div></div></section>
  <section id="projets" className="section"><div className="container"><div className="head"><div><span className="line"/><h2>Projets & réalisations</h2><p>Un espace dynamique pour publier chaque année les projets, activités, résultats et réalisations de SALAAM.</p></div></div>{d.projects?.length?<div className="projectGrid">{d.projects.map((p:any)=><article className="feature" key={p.id}><div className="featureImg">{p.imageUrl&&<img src={p.imageUrl} alt=""/>}</div><div className="featureBody"><span className="badge">{p.status}</span><h3>{p.title}</h3><p>{p.summary}</p></div></article>)}</div>:<div className="notice">Les projets détaillés seront ajoutés par l’administration dès que les informations officielles seront disponibles.</div>}</div></section>
  <section id="actualites" className="section alt"><div className="container"><div className="head"><div><span className="line"/><h2>Actualités</h2><p>Communications, événements, annonces et nouvelles de l’organisation.</p></div></div>{d.news?.length?<div className="newsGrid">{d.news.map((n:any)=><article className="feature" key={n.id}><div className="featureImg">{n.imageUrl&&<img src={n.imageUrl} alt=""/>}</div><div className="featureBody"><span className="badge">Actualité</span><h3>{n.title}</h3><p>{n.excerpt}</p></div></article>)}</div>:<div className="notice">Aucune actualité n’a encore été publiée. L’administration pourra en ajouter à tout moment depuis le tableau de bord.</div>}</div></section>
  <section className="section"><div className="container"><div className="head"><div><span className="line"/><h2>Galerie</h2><p>Images d’activités et de la vie de l’organisation.</p></div></div><div className="gallery">{d.gallery?.map((g:any)=><figure key={g.id??g[0]}><img src={g.imageUrl||g[1]} alt={g.title||g[0]}/><figcaption>{g.caption||g[2]||g.title}</figcaption></figure>)}</div></div></section>
  <section id="contact" className="section contact"><div className="container"><div className="head"><div><span className="line"/><h2>Contactez-nous</h2><p>Pour toute information, collaboration ou demande concernant les activités de l’ONGD SALAAM.</p></div></div><div className="contactGrid"><div className="contactBox"><h3>Coordonnées</h3><div className="row"><div>📍</div><div><b>Adresse</b><span>{s.address}</span></div></div><div className="row"><div>✉️</div><div><b>Email</b><span><a href={`mailto:${s.email}`}>{s.email}</a></span></div></div><div className="row"><div>☎️</div><div><b>WhatsApp / Téléphone</b><span><a href={`https://wa.me/${s.phone.replace(/\D/g,'')}`} target="_blank" rel="noopener noreferrer">{s.phone}</a></span></div></div></div><div className="contactBox"><h3>Réseaux officiels</h3><p style={{color:'var(--muted)'}}>Les liens communiqués par l’organisation sont intégrés ici. D’autres plateformes pourront être ajoutées depuis l’administration.</p><div className="socials">{(d.social?.length?d.social:[['WhatsApp Channel',s.whatsapp,'WhatsApp'],['LinkedIn',s.linkedin,'LinkedIn']]).map((x:any)=><a className="social" key={x.id??x[0]} href={x.url||x[1]} target="_blank">{x.label||x[0]}</a>)}</div></div></div></div></section>
  <footer><div className="container"><div className="footerGrid"><div><div className="brand"><img src="/assets/logo.jpg" alt="Logo"/><div><b style={{color:'#fff'}}>ONGD SALAAM</b><small style={{color:'#cbdbea'}}>Solidarité · Assistance · Accompagnement<br/>Amitié · Paix</small></div></div><p style={{fontSize:12}}>Une organisation basée à Gbadolite, engagée pour la paix, la protection, l’éducation, l’action humanitaire et le développement communautaire.</p></div><div><h4>Navigation</h4><Link href="#apropos">À propos</Link><Link href="#actions">Nos actions</Link><Link href="#equipe">Notre équipe</Link><Link href="#projets">Projets</Link><Link href="#actualites">Actualités</Link></div><div><h4>Réseaux</h4>{(d.social?.length?d.social:[['WhatsApp Channel',s.whatsapp],['LinkedIn',s.linkedin]]).map((x:any)=><a key={x.id??x[0]} href={x.url||x[1]} target="_blank">{x.label||x[0]}</a>)}</div><div><h4>Administration</h4><Link href="/admin">Accès au tableau de bord</Link><a href={`mailto:${s.email}`}>{s.email}</a><a href="#contact">{s.address}</a></div></div><div className="copy"><span>© {new Date().getFullYear()} ONGD SALAAM. Tous droits réservés.</span><span>Site dynamique · contenu évolutif administrable.</span></div></div></footer>
 </>
}
